# check whether the training needed or inference needed
mode: "train" # train or inference
best_checkpoint_path: "checkpoints/best-checkpoint.ckpt"


folder:
    dataset: "dataset"
    logs: "logs"
    checkpoints: "checkpoints"

# split ratio for train, val and test
split_ratio:
    train: 0.8
    val: 0.1
    test: 0.1

# dataloader config
dataloader:
    num_workers: 7
    pin_memory: true
    batch_size: 32

# model config
model:
    name: "resnet18"
    pretrained: true
    num_classes: 10

# optimizer config
optimizer:
    name: "adam"
    lr: 0.001
    weight_decay: 0.0001

trainer:
    max_epochs: 3
    precision: 16
    accelerator: "mps"
    devices: 1

